### ISSUE TITLE
Checking client_id against audience

### ISSUE THREAD

**Issue by marcodallasanta** [GioPat/cognito-jwt-verify#3]
Hi Gio, 
as the title says I'm interested in why are checking the client_id against the audience? 

The first is the id of the client who's trying to authenticate itself, the latter (aud claim) is the resource you are trying to access.

Is there any reason why you did it other than a practical one?

Cheers.

**Comment by GioPat** [comment]
Hello Marco 👋 
the check is relative to the step 3 - Point no 3 of the documentation to validate the JWT token that you can find at [this link](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html).

The reason behind it (I'm not a JWT expert) is the check that the token you are validating has been granted specifically for the App client ID that you are expecting.
